name: Publish

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Setup-Checkout
      uses: actions/checkout@v2

    - name: Setup-Dotnet 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      
    - name: Setup-Dotnet 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Setup-Msbuild
      uses: microsoft/setup-msbuild@v1
     
    - name: Setup-Monogame
      run: dotnet tool install -g dotnet-mgcb
      
    - name: Restore-Nuget
      run: msbuild Seihou /t:restore
      
    - name: Build-All
      run: msbuild Seihou /verbosity:normal /t:Rebuild /p:Configuration=Release
      
    - name: Remove debug files
      run: del ./Seihou/bin/Release/net6.0/win-x64/publish/*.pdb
      
    - name: Remove jsons
      run: del ./Seihou/bin/Release/net6.0/win-x64/publish/*.json
      
    - name: Publish-Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Seihou.exe
        path:  ./Seihou/bin/Release/net6.0/win-x64/publish
        retention-days: 5
