name: Publish

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Setup-Checkout
      uses: actions/checkout@v2

    - name: Setup-Dotnet 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      
    - name: Setup-Dotnet 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
   
    - name: Setup-Monogame
      run: dotnet tool install -g dotnet-mgcb 
      
    - name: Restore dependencies
      run: dotnet restore Seihou
      
    - name: Build-All
      run: dotnet publish seihou -p:PublishSingleFile=true -r win-x64 -c Release --self-contained true
      
    - name: Remove debug files
      run: del ./seihou/Seihou/bin/Release/net6.0-windows/win-x64/publish/*.pdb
      
    - name: Publish-Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Seihou.exe
        path:  ./seihou/Seihou/bin/Release/net6.0-windows/win-x64/publish
        retention-days: 5
