name: Build-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Setup-Checkout
      uses: actions/checkout@v2

    - name: Setup-Dotnet 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      
    - name: Setup-Dotnet 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Setup-Msbuild
      uses: microsoft/setup-msbuild@v1
     
    - name: Setup-Monogame
      run: dotnet tool install -g dotnet-mgcb
      
    - name: Restore-Nuget
      run: msbuild Seihou /t:restore
      
    - name: Build-All
      run: msbuild Seihou /verbosity:normal /t:Rebuild /p:Configuration=Release
